In [102]:
from IPython.display import display, Math
import numpy
import pandas
import sympy

Mean = middle of data

In [103]:
x = [ 1, 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]
sum_x = numpy.sum(x)
len_x = len(x)

mean = sum_x / len_x
display(Math("\\frac{\\sum x}{y} = %g" %mean))
numpy.mean(x)

<IPython.core.display.Math object>

7.5

Median = sort and find middle of data

In [104]:
odd = numpy.array([2, 4, 6, 8, 10])
even = numpy.array([1, 3, 5, 7, 9])

sorted_odd = numpy.sort(odd)
sorted_even = numpy.sort(even)

median_odd = numpy.sum(sorted_odd) / len(sorted_odd)
median_even = even[0] + even[-1] / 2

print(f"{sorted_odd} = {median_odd}")
print(f"{sorted_even} = {median_even}")

[ 2  4  6  8 10] = 6.0
[1 3 5 7 9] = 5.5


Modus = find most duplicate value

In [105]:
randInt = numpy.random.randint(0, 10, 15)
randInt

array([8, 6, 2, 4, 2, 8, 2, 7, 8, 7, 6, 5, 9, 2, 0])

Sum = Addition in List

In [106]:
randInt = numpy.arange(1, 10)
numpy.sum(randInt)

45

Std

In [107]:
data = { 'A': [1, 2, 3, 4, 5] }
df = pandas.DataFrame(data)

mean_value = df["A"].mean()
diff_from_mean = df["A"] - mean_value
squared_diff = diff_from_mean ** 2
sum_squared_diff = squared_diff.sum()

squared_diff_len = len(df)
std_deviation = (sum_squared_diff / (squared_diff_len - 1)) ** 0.5
std_deviation

1.5811388300841898

25% = <i>25% from beginning of data</i> <br>
50% = <i>50% from beginning of data</i> <br>
75% = <i>75% from beginning of data</i>

In [108]:
# data = numpy.array([7, 3, 1, 6, 6, 8, 4, 3, 5, 2])
data = numpy.arange(1, 16)
df = pandas.DataFrame(data)
print(data)
df.describe()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


0
count  15.000000
mean    8.000000
std     4.472136
min     1.000000
25%     4.500000
50%     8.000000
75%    11.500000
max    15.000000

Count = Length of List

In [109]:
data = numpy.arange(0, 7)
pandas.DataFrame(data).count()

0    7
dtype: int64

Mode = Get duplicated value from column

In [110]:
data = pandas.DataFrame({
    "A": numpy.random.randint(0, 10, 10),
    "B": numpy.random.randint(0, 10, 10),
    "C": numpy.random.randint(0, 10, 10),
})

print(data.transpose())
data.mode()

   0  1  2  3  4  5  6  7  8  9
A  2  2  1  9  8  1  6  3  3  9
B  7  8  5  4  2  1  5  8  4  1
C  8  9  7  4  3  6  6  7  4  5


A  B    C
0  1  1  4.0
1  2  4  6.0
2  3  5  7.0
3  9  8  NaN

Abs = Negative (-) Number to Positive (+)

In [111]:
data = {
    'A': [-2, -1, 0, 1, 2],
    'B': [-3, -2, -1, 0, 1]
}

pandas.DataFrame(data).abs()

A  B
0  2  3
1  1  2
2  0  1
3  1  0
4  2  1

Min = <i>Minimum Number</i><br>
Min = <i>Maximum Number</i><br>

In [112]:
data = numpy.arange(1, 25)
print(data)

print(f"Min: {data.min()}")
print(f"Max: {data.max()}")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Min: 1
Max: 24


Prod = Multiple value in list

In [113]:
data = [1, 2, 3, 4, 5]
df = pandas.DataFrame(data)
print(data)
df.prod().loc[0]

[1, 2, 3, 4, 5]


120

Cumsum = addition data from <i>left - axis=1</i> | <i>top - axis=0</i>

In [175]:
data = numpy.array([numpy.random.randint(0, 10, 5) for i in range(3)])
display(Math(sympy.latex(sympy.simplify(data))))
numpy.cumsum(data, axis=1)

<IPython.core.display.Math object>

array([[ 4,  7, 14, 20, 25],
       [ 7, 11, 11, 17, 25],
       [ 7,  7, 15, 16, 24]])

Cumsum = multiply data from <i>left - axis=1</i> | <i>top - axis=0</i>

In [177]:
data = numpy.array([numpy.random.randint(0, 10, 5) for i in range(3)])
display(Math(sympy.latex(sympy.simplify(data))))
numpy.cumprod(data, axis=0)

<IPython.core.display.Math object>

array([[  2,   2,   8,   2,   4],
       [  2,   6,  24,   2,   0],
       [ 14,  18, 168,  16,   0]])